/**
 * Spintax (Spin Syntax) Parser & Evaluator
 *
 * Supports nested Spintax syntax like `{Hello|Hi|Hey} {there|friend|{{Name}}}`.
 * Selects random variants recursively or with a deterministic seed/index.
 */

const SPINTAX_PATTERN = /\{([^{}]+)\}/g;

/**
 * Resolve spintax patterns in a string.
 * Example:
 *   parseSpintax("{Hi|Hello} {{Name}}!") => "Hello {{Name}}!" or "Hi {{Name}}!"
 *
 * Supports nested expressions:
 *   "{Good {morning|day}|Welcome}" => "Good morning" or "Good day" or "Welcome"
 *
 * @param text The input string containing spintax blocks {option1|option2|...}
 * @param rng Optional random generator returning [0, 1) (defaults to Math.random)
 */
export function parseSpintax(text: string, rng: () => number = Math.random): string {
  if (!text || typeof text !== 'string') return text;

  let current = text;
  let hasMatches = true;
  let safetyLimit = 20; // prevent runaway loops with nested depths

  while (hasMatches && safetyLimit > 0) {
    safetyLimit--;
    const previous = current;
    current = current.replace(SPINTAX_PATTERN, (_match, group: string) => {
      // Check if it's a spintax group (contains | separator)
      if (!group.includes('|')) {
        // Not a spintax choice (might be another brace format like {variable})
        return `{${group}}`;
      }
      const choices = group.split('|');
      const chosenIdx = Math.floor(rng() * choices.length);
      return choices[chosenIdx];
    });

    hasMatches = current !== previous && SPINTAX_PATTERN.test(current);
  }

  return current;
}

/**
 * Calculate the total number of unique combinations generated by a spintax string.
 */
export function countSpintaxVariations(text: string): number {
  if (!text || typeof text !== 'string') return 1;

  let total = 1;
  const matches = text.match(SPINTAX_PATTERN);
  if (!matches) return 1;

  for (const match of matches) {
    const inner = match.slice(1, -1);
    if (inner.includes('|')) {
      const options = inner.split('|').length;
      total *= Math.max(1, options);
    }
  }

  return total;
}
