apiVersion: v1
kind: Service
metadata:
  name: {{ include "leadweave.fullname" . }}-headless
  labels:
    {{- include "leadweave.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "leadweave.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 2785
      targetPort: http
